# pipelines/crash-classifier.yml
trigger:
  branches:
    include:
      - dev
      - main
  paths:
    include:
      - apps/crash-classifier/**
      - pipelines/crash-classifier.yml
      - pipelines/templates/function-app.yml

variables:
  - name: FUNCTION_APP_NAME
    value: $(FUNC_CRASH_CLASSIFIER_NAME)
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/dev') }}:
    - group: guardianlink-infra-outputs
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    - group: guardianlink-infra-outputs-prod

stages:
  - template: templates/function-app.yml
    parameters:
      appDir: apps/crash-classifier
