# pipelines/telemetry-writer.yml
trigger:
  branches:
    include:
      - dev
      - main
  paths:
    include:
      - apps/telemetry-writer/**
      - pipelines/telemetry-writer.yml
      - pipelines/templates/function-app.yml

variables:
  - name: FUNCTION_APP_NAME
    value: $(FUNC_TELEMETRY_WRITER_NAME)
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/dev') }}:
    - group: guardianlink-infra-outputs
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    - group: guardianlink-infra-outputs-prod

stages:
  - template: templates/function-app.yml
    parameters:
      appDir: apps/telemetry-writer
