apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: consumer-secrets
  namespace: consumer
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "${CONSUMER_IDENTITY_CLIENT_ID}"
    keyvaultName: "${KV_NAME}"
    tenantId: "${AZURE_TENANT_ID}"
    objects: |
      array:
        - |
          objectName: appi-connection-string
          objectType: secret
          objectAlias: APPLICATIONINSIGHTS_CONNECTION_STRING
  secretObjects:
    - secretName: consumer-secrets
      type: Opaque
      data:
        - objectName: APPLICATIONINSIGHTS_CONNECTION_STRING
          key: APPLICATIONINSIGHTS_CONNECTION_STRING
