apiVersion: v1
kind: ServiceAccount
metadata:
  name: consumer-sa
  namespace: consumer
  annotations:
    azure.workload.identity/client-id: "${CONSUMER_IDENTITY_CLIENT_ID}"
  labels:
    azure.workload.identity/use: "true"
    app.kubernetes.io/part-of: guardianlink
